### ISSUE TITLE
Build fails on Linux due to dangling reference warnings

### ISSUE THREAD

**Issue by chizkiyahu** [arm/ai-ml-sdk-scenario-runner#58]
Starting from commit `2e3d0a5` (introduced in PR #35), the Linux build fails because of `-Werror` treating warnings as errors.  
The problem appears in `src/json_reader.cpp`, with multiple instances of:

```

error: possibly dangling reference to a temporary \[-Werror=dangling-reference]
/home/runner/work/ai-ml-sdk-scenario-runner/ai-ml-sdk-scenario-runner/sw/scenario-runner/src/json\_reader.cpp:223:17: error: possibly dangling reference to a temporary \[-Werror=dangling-reference]
223 |     const json \&bindingsJson = j.find("bindings").value();
\|                 ^\~\~\~\~\~\~\~\~\~\~\~

```

Full log: [GitHub Actions run](https://github.com/Chizkiyahu/ai-ml-sdk-scenario-runner/actions/runs/17408916361/job/49420748953)

This issue occurs only on Linux builds due to stricter compiler checks with `-Werror`.

@nlithammer

**Comment by nlithammer** [comment]
Hi!
Yes, my bad. Will fix.
Thanks
